### ISSUE TITLE
Not able to connect to pytesthistoric on 0.0.0.0:5000

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-historic#1]
![image](https://user-images.githubusercontent.com/12759282/76169032-991e9e80-619a-11ea-99ff-18c2a20d6365.png)

![image](https://user-images.githubusercontent.com/12759282/76169036-a3409d00-619a-11ea-9b0c-21ef2473e49d.png)

installation of pytest-historic, mysqldb and all other relevant steps have been successfully performed.

**Comment by adiralashiva8** [comment]
Try this: localhost:5000

**Comment by adiralashiva8** [comment]
@parwalrahul  Updated wiki step
![image](https://user-images.githubusercontent.com/12430515/76195086-8ee9b800-620d-11ea-9d3d-4983876ccd61.png)

**Comment by parwalrahul** [comment]
closing issue as documentation is updated.
