### ISSUE TITLE
Need to center align "description" column to maintain uniformity in table

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-historic#11]
Refer Screenshot :
![image](https://user-images.githubusercontent.com/12759282/76336684-5edd0a80-631c-11ea-95e3-9f2c41fcbb98.png)

**Comment by adiralashiva8** [comment]
Agree but sometime user can use description to explain more about execution 

Ex: `Smoketest on build v0.3 in Windows 10 - dev #1237845 user story changes`. 

In the above example displaying description in `Center` align will make UI bit ugly

**Comment by parwalrahul** [comment]
Agreed. In the above case, can we wrap the text if length exceeds some characters (say 15 or 20)

**Comment by adiralashiva8** [comment]
Closing issue
