### ISSUE TITLE
Flaky test Link of (N)th Recent Execution redirects to empty page if we delete the (N-1)th Execution.

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-historic#13]
Steps to Reproduce:
1. Run Test Execution with description "A" (say EID = 2)
2. Run Test Execution with description "B" (say EID = 3)
3. Delete Test Execution (EID = 2) from history tab
4. Navigate to FlakyTest Section
5. Click  on the Recent Execution Link (Representing the Nth Execution)
6. You will navigate to the empty page. Refer Screenshot below :

![image](https://user-images.githubusercontent.com/12759282/76339132-b466e680-631f-11ea-843a-f4c522ca30c9.png)

**Comment by adiralashiva8** [comment]
Fixed as part of https://github.com/adiralashiva8/pytest-historic/commit/e987b347e1e192915a33382abc27e149688cd408 commit
