### ISSUE TITLE
Need to update the hover message on the Recent, Recent -1, Recent - 2 etc. on Flaky tests screen to make them meaningful

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-historic#14]
Current Hover Screenshot :
![image](https://user-images.githubusercontent.com/12759282/76339517-32c38880-6320-11ea-8a2b-78b9b5d15c86.png)

Current Hover Message (on Recent Link): **Click to view "N " Execution info.** (In my case N = 2 but latest execution id = 4, i deleted execution id 2 and 3 records).

Expected Hover Message : Click to view EID : <EID Number> Execution Info [ having Description as <Description>]

[Description part is optional]

**Comment by adiralashiva8** [comment]
Fixed as part of https://github.com/adiralashiva8/pytest-historic/commit/e987b347e1e192915a33382abc27e149688cd408 commit
