### ISSUE TITLE
Need to mention authentication method in documentation of MySQL Setup Guide (8 and above)

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-historic#3]
The default authentication method created issue with sha authentication.

Refer Below Image for the authentication mode the user needs to select :

![image](https://user-images.githubusercontent.com/12759282/76303881-73071480-62e8-11ea-9524-a8a956fdff98.png)

**Comment by adiralashiva8** [comment]
Added *Step 5* [here](https://github.com/adiralashiva8/pytest-historic/wiki/1.-MySQL-Setup-Guide) - thanks for notifying

**Comment by parwalrahul** [comment]
Please add this step between step 2 and 3 not in Step 5.
