### ISSUE TITLE
Need to update console log to update Address of pytesthistoric from 0.0.0.0:50000 to locatohost:5000 or 127.0.0.1:5000

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-historic#4]
Refer Screenshot below :

![image](https://user-images.githubusercontent.com/12759282/76304250-122c0c00-62e9-11ea-95dd-a3f6782ef073.png)

**Comment by adiralashiva8** [comment]
Above log is auto generated by `Flask`, we are intentionaly starting app in `0.0.0.0:5000` so app can be accessed within LAN (others can also access to report using hostip:5000)

**Comment by adiralashiva8** [comment]
Closing this issue since we dont modify it (but updated in wiki)
