### ISSUE TITLE
db error while creating new project in pytesthistoric

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-historic#5]
Steps to Reproduce:
1. Run pytesthistoric
2. Navigate to 127.0.0.1:5000 on Chrome Browser
3. Click on "Get Started" Button

![image](https://user-images.githubusercontent.com/12759282/76304423-633c0000-62e9-11ea-971c-0a957941797f.png)

4. On the Home Page, Click on New Project Button

![image](https://user-images.githubusercontent.com/12759282/76304464-73ec7600-62e9-11ea-88c7-a846bf3daf68.png)

5. Enter Project Name as : test, Description as test and hit create button.

![image](https://user-images.githubusercontent.com/12759282/76304563-97172580-62e9-11ea-8c1f-4ea59b2ec64b.png)

**Issue :** The project is not created on the pytesthistoric homepage.

**Console Logs :**
![image](https://user-images.githubusercontent.com/12759282/76304727-de9db180-62e9-11ea-96c4-280b43e6e705.png)

(1054, "Unknown column 'Overall_Pass_Perc' in 'field list'")

**Comment by adiralashiva8** [comment]
My Bad, I forgot to include one more table column `overall_pass_perc` in wiki, now I have updated wiki, Please delete the `tb_project table` and re-create it using following command.

```
Create table TB_PROJECT ( Project_Id INT NOT NULL auto_increment primary key, Project_Name TEXT, Project_Desc TEXT, Project_Image TEXT, Created_Date DATETIME, Last_Updated DATETIME, Total_Executions INT, Recent_Pass_Perc FLOAT, Overall_Pass_Perc FLOAT);
```

**Comment by parwalrahul** [comment]
closing issue as this works now.
