### ISSUE TITLE
[Documentation Error] Need to reorder the steps mentioned in readme.md for Installation

### ISSUE THREAD

**Issue by parwalrahul** [adiralashiva8/pytest-historic#7]
Need to swap step 1 and step 2 as MySQL installation is a prerequisite for installing pytesthistoric.

Refer Screenshot below :

![image](https://user-images.githubusercontent.com/12759282/76333807-25a29b80-6318-11ea-8b00-3c225b063d7a.png)

**Comment by adiralashiva8** [comment]
Updated readme.md as suggested and closing this issue
